server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:

  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/user_dbs
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect

